theme: jekyll-theme-minimal
title: Duy Nguyen's blog
description: Personal blog to discuss what I have done and learned through my research and study
logo: /assets/logo.jpg
paginate: 7
paginate_path: "/page-:num/"

contact:
  - name: Email
    icon: "fas fa-at"
    value: mailto:duynguyen269@skku.edu
  - name: LinkedIn
    icon: "fab fa-linkedin"
    value: https://www.linkedin.com/in/duynguyen-ori75/
  - name: GitHub
    icon: "fab fa-github-square"
    value: https://github.com/duynguyen-ori75

resume_url: https://github.com/duynguyen-ori75/resume/raw/master/resume.pdf

plugins:
  - jekyll-paginate