theme: jekyll-theme-minimal
title: Duy Nguyen
description: Welcome to my personal blog

contact:
  - name: Email
    icon: "fas fa-at"
    value: duynguyen.ori75@gmail.com
  - name: LinkedIn
    icon: "fab fa-linkedin"
    value: https://www.linkedin.com/in/duynguyen-ori75/
  - name: GitHub
    icon: "fab fa-github-square"
    value: https://github.com/duynguyen-ori75