theme: jekyll-theme-minimal
title: Duy Nguyen's blog
description: Funny stuffs - mostly about database systems and distributed computing
logo: /assets/logo.jpg
paginate: 5
paginate_path: "/page-:num/"

contact:
  - name: Email
    icon: "fas fa-at"
    value: mailto:duynguyen269@skku.edu
  - name: LinkedIn
    icon: "fab fa-linkedin"
    value: https://www.linkedin.com/in/duynguyen-ori75/
  - name: GitHub
    icon: "fab fa-github-square"
    value: https://github.com/duynguyen-ori75

plugins:
  - jekyll-paginate